import type { AnalyzeApiResult } from "./apiTypes";

export function buildMarkdownReport(result: AnalyzeApiResult): string {
  const { scoring, issues, page } = result;
  const lines: string[] = [];

  lines.push(`# AI Agent Readiness Report`);
  lines.push("");
  lines.push(`**URL:** ${result.finalUrl}`);
  lines.push(`**Scanned:** ${result.fetchedAt}`);
  lines.push(`**Score:** ${scoring.overallScore}/100 — ${scoring.status}`);
  if (scoring.downgradedByBlocker) {
    lines.push(`_Score alone would read "Agent Ready", held at "Mostly Ready" by a Critical Blocker._`);
  }
  lines.push(`_Computed from ${scoring.scoredWeight}/100 spec points — the rest needs runtime or visual inspection._`);
  lines.push("");

  lines.push(`## Category scores`);
  lines.push("");
  lines.push(`| Category | Score | Pass | Partial | Fail | N/A |`);
  lines.push(`| --- | --- | --- | --- | --- | --- |`);
  for (const cat of scoring.categories) {
    lines.push(
      `| ${cat.label} | ${cat.hasData ? `${Math.round(cat.percentage)}%` : "—"} | ${cat.passCount} | ${cat.partialCount} | ${cat.failCount} | ${cat.naCount} |`
    );
  }
  lines.push("");

  if (scoring.criticalBlockers.length > 0) {
    lines.push(`## Critical Agent Blockers`);
    lines.push("");
    for (const b of scoring.criticalBlockers) {
      lines.push(`- **${b.title}** — ${b.detail}`);
    }
    lines.push("");
  }

  lines.push(`## Issues (${issues.length})`);
  lines.push("");
  for (const issue of issues) {
    lines.push(`### ${issue.severity === "critical" ? "🔴" : "🟠"} ${issue.title} (−${issue.scoreImpact})`);
    lines.push(`- **Category:** ${issue.category}`);
    if (issue.example) lines.push(`- **Found on this page:** \`${issue.example}\``);
    lines.push(`- **Why this matters:** ${issue.why}`);
    lines.push(`- **How to fix:** ${issue.fix}`);
    lines.push("");
  }

  lines.push(`## Page summary`);
  lines.push("");
  lines.push(`- Title: ${page.title ?? "(none)"}`);
  lines.push(`- Headings: ${page.counts.headings}, Links: ${page.counts.links}, Buttons: ${page.counts.buttons}`);
  lines.push(`- Forms: ${page.counts.forms} (${page.counts.formFields} fields), Images: ${page.counts.images}`);
  lines.push(`- JSON-LD blocks: ${page.counts.structuredData}`);
  lines.push("");
  lines.push(`---`);
  lines.push(`_Generated by AgentReady — structural agent readiness only, not a guarantee of task success._`);

  return lines.join("\n");
}

export function downloadTextFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slugFromUrl(url: string): string {
  return url.replace(/^https?:\/\//, "").replace(/[^a-z0-9]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase();
}

export function exportReportAsMarkdown(result: AnalyzeApiResult) {
  downloadTextFile(
    `agentready-${slugFromUrl(result.finalUrl)}.md`,
    buildMarkdownReport(result),
    "text/markdown"
  );
}

export function exportReportAsJson(result: AnalyzeApiResult) {
  downloadTextFile(
    `agentready-${slugFromUrl(result.finalUrl)}.json`,
    JSON.stringify(result, null, 2),
    "application/json"
  );
}
